import { Participant, ProgramSession, PartnerOrganization } from './types';

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'part-1',
    firstName: 'Tendai',
    lastName: 'Chikwanha',
    organization: 'Youth Empowerment Trust',
    subPartnerProgramArea: 'Youth Livelihoods & Skills',
    role: 'Partner',
    email: 'tendai.c@yetrust.org.zw',
    phoneNumber: '+263 77 123 4567',
    dietaryRequirements: 'Vegetarian',
    accessibilityRequirements: 'None',
    travelRequirements: 'Harare Local Transport',
    accommodationRequirements: 'Not required',
    registrationId: 'REG-OAK-1001',
    registrationDate: '2026-09-08',
    qrCodeId: 'QR-OAK-PARTNER-1001',
    registrationStatus: 'Registered',
    attendanceStatus: 'Attended',
    checkInTime: '08:15 AM',
    checkInDate: '9 November 2026',
  },
  {
    id: 'part-2',
    firstName: 'Ruvimbo',
    lastName: 'Moyo',
    organization: 'Child Rights Coalition Zimbabwe',
    subPartnerProgramArea: 'Child Protection & Advocacy',
    role: 'Partner',
    email: 'ruvimbo.moyo@crcz.org.zw',
    phoneNumber: '+263 71 234 5678',
    dietaryRequirements: 'Halal',
    accessibilityRequirements: 'Wheelchair access required',
    travelRequirements: 'Bulawayo to Harare Flight',
    accommodationRequirements: 'Cresta Lodge (2 Nights)',
    registrationId: 'REG-OAK-1002',
    registrationDate: '2026-09-08',
    qrCodeId: 'QR-OAK-PARTNER-1002',
    registrationStatus: 'Registered',
    attendanceStatus: 'Not Attended',
    checkInTime: null,
    checkInDate: null,
  },
  {
    id: 'part-3',
    firstName: 'Farai',
    lastName: 'Ndlovu',
    organization: 'OAK Foundation',
    subPartnerProgramArea: 'Grant Management',
    role: 'OAK Staff',
    email: 'farai.ndlovu@oakfnd.org',
    phoneNumber: '+263 77 345 6789',
    dietaryRequirements: 'None (Standard)',
    accessibilityRequirements: 'None',
    travelRequirements: 'International Flight',
    accommodationRequirements: 'Cresta Lodge (3 Nights)',
    registrationId: 'REG-OAK-1003',
    registrationDate: '2026-09-07',
    registrationStatus: 'Registered',
    attendanceStatus: 'Attended',
    checkInTime: '08:00 AM',
    checkInDate: '9 November 2026',
  },
  {
    id: 'part-4',
    firstName: 'Elisha',
    lastName: 'Urombo',
    organization: 'OAK Foundation Coordination Hub',
    subPartnerProgramArea: 'Event & Technical Lead',
    role: 'Coordination Team',
    email: 'elisha.u@oakcoordination.org',
    phoneNumber: '+263 78 456 7890',
    dietaryRequirements: 'None',
    accessibilityRequirements: 'None',
    travelRequirements: 'Local',
    accommodationRequirements: 'Cresta Lodge (Event Ops)',
    registrationId: 'REG-OAK-1004',
    registrationDate: '2026-09-07',
    registrationStatus: 'Registered',
    attendanceStatus: 'Attended',
    checkInTime: '07:30 AM',
    checkInDate: '9 November 2026',
  },
  {
    id: 'part-5',
    firstName: 'Dr. Sarah',
    lastName: 'Mandaza',
    organization: 'University of Zimbabwe / Policy Institute',
    subPartnerProgramArea: 'Education Research',
    role: 'Presenter',
    email: 'dr.mandaza@uz.ac.zw',
    phoneNumber: '+263 73 567 8901',
    dietaryRequirements: 'Gluten-Free',
    accessibilityRequirements: 'Audio-visual presentation assistance',
    travelRequirements: 'Local Harare',
    accommodationRequirements: 'None',
    registrationId: 'REG-OAK-1005',
    registrationDate: '2026-09-09',
    registrationStatus: 'Registered',
    attendanceStatus: 'Not Attended',
    checkInTime: null,
    checkInDate: null,
  },
  {
    id: 'part-6',
    firstName: 'Blessing',
    lastName: 'Tshuma',
    organization: 'Regional Development Monitor',
    subPartnerProgramArea: 'Civil Society Monitoring',
    role: 'Observer',
    email: 'b.tshuma@devmonitor.org',
    phoneNumber: '+263 77 678 9012',
    dietaryRequirements: 'None',
    accessibilityRequirements: 'None',
    travelRequirements: 'Mutare to Harare Coach',
    accommodationRequirements: 'Cresta Lodge (2 Nights)',
    registrationId: 'REG-OAK-1006',
    registrationDate: '2026-09-09',
    registrationStatus: 'Registered',
    attendanceStatus: 'Attended',
    checkInTime: '08:30 AM',
    checkInDate: '9 November 2026',
  },
  {
    id: 'part-7',
    firstName: 'Tinashe',
    lastName: 'Gumbo',
    organization: 'Eco-Justice Network Zimbabwe',
    subPartnerProgramArea: 'Climate Resilience & Livelihoods',
    role: 'Partner',
    email: 'tinashe.g@ecojustice.org.zw',
    phoneNumber: '+263 71 789 0123',
    dietaryRequirements: 'Vegetarian',
    accessibilityRequirements: 'None',
    travelRequirements: 'Masvingo to Harare',
    accommodationRequirements: 'Cresta Lodge (2 Nights)',
    registrationId: 'REG-OAK-1007',
    registrationDate: '2026-09-10',
    qrCodeId: 'QR-OAK-PARTNER-1007',
    registrationStatus: 'Registered',
    attendanceStatus: 'Attended',
    checkInTime: '08:42 AM',
    checkInDate: '9 November 2026',
  },
];

export const INITIAL_PROGRAM_SESSIONS: ProgramSession[] = [
  // Day 1: 9 November 2026
  {
    id: 'sess-1',
    date: '9 November 2026',
    dayNumber: 1,
    time: '08:00 AM - 09:00 AM',
    sessionTitle: 'Registration, Welcome Coffee & Partner Networking',
    speaker: 'Coordination Team & OAK Staff',
    speakerRole: 'Event Host Team',
    speakerBio: 'The coordination committee facilitating registration verification and welcoming delegates.',
    venue: 'Cresta Lodge Courtyard & Foyer',
    sessionDescription: 'Arrival of delegates, verification of partner credentials, badge collection, morning refreshments, and informal networking.',
  },
  {
    id: 'sess-2',
    date: '9 November 2026',
    dayNumber: 1,
    time: '09:00 AM - 10:30 AM',
    sessionTitle: 'Opening Plenary: OAK Foundation Vision & Strategic Priorities',
    speaker: 'Farai Ndlovu & Regional Leadership',
    speakerRole: 'Head of Regional Programs, OAK Foundation',
    speakerBio: 'Leading strategic grantmaking and philanthropic partnerships across Southern Africa.',
    venue: 'Main Conference Hall',
    sessionDescription: 'Official welcome remarks, celebration of partner milestones, strategic direction for the 2026-2030 funding framework, and convening objectives.',
  },
  {
    id: 'sess-3',
    date: '9 November 2026',
    dayNumber: 1,
    time: '11:00 AM - 12:30 PM',
    sessionTitle: 'Panel: Strengthening Community-Led Impact in Zimbabwe',
    speaker: 'Dr. Sarah Mandaza & Partner Representatives',
    speakerRole: 'Lead Policy Researcher',
    speakerBio: 'Specialist in grassroots civil society impact measurement and institutional strengthening.',
    venue: 'Main Conference Hall',
    sessionDescription: 'Interactive panel featuring grassroots partners sharing key breakthroughs, community resilience models, and sustainability strategies.',
  },
  {
    id: 'sess-4',
    date: '9 November 2026',
    dayNumber: 1,
    time: '02:00 PM - 04:00 PM',
    sessionTitle: 'Breakout Sessions: Thematic Collaboration Hubs',
    speaker: 'Thematic Facilitators',
    speakerRole: 'Civil Society Working Groups',
    speakerBio: 'Group leads across Education, Child Rights, Climate Justice, and Youth Empowerment.',
    venue: 'Breakout Rooms A, B & Msasa Room',
    sessionDescription: 'Deep-dive working group sessions focused on joint programming, cross-learning between sub-partners, and addressing shared operational barriers.',
  },

  // Day 2: 10 November 2026
  {
    id: 'sess-5',
    date: '10 November 2026',
    dayNumber: 2,
    time: '08:30 AM - 10:00 AM',
    sessionTitle: 'Keynote: Navigating Regulatory & Civic Space in Southern Africa',
    speaker: 'Advocate Tendai Biti & Legal Experts',
    speakerRole: 'Civic Space & Legal Analyst',
    speakerBio: 'Renowned expert in NGO governance, compliance frameworks, and civic space protection.',
    venue: 'Main Conference Hall',
    sessionDescription: 'Practical insights into compliance, organizational safety, safeguarding, and navigating regulatory frameworks effectively.',
  },
  {
    id: 'sess-6',
    date: '10 November 2026',
    dayNumber: 2,
    time: '10:30 AM - 12:30 PM',
    sessionTitle: 'Workshop: Digital Storytelling, MEL & Accountability',
    speaker: 'Chipo Muzenda',
    speakerRole: 'Monitoring & Evaluation Lead',
    speakerBio: 'Pioneering impact storytelling and participatory monitoring systems for humanitarian organizations.',
    venue: 'Msasa Room',
    sessionDescription: 'Hands-on workshop on capturing authentic impact narratives, participatory evaluation metrics, and transparent funder reporting.',
  },
  {
    id: 'sess-7',
    date: '10 November 2026',
    dayNumber: 2,
    time: '02:00 PM - 04:30 PM',
    sessionTitle: 'Partner Showcase & Knowledge Exchange Market',
    speaker: 'All Participating Partners',
    speakerRole: 'Partner Organizations',
    speakerBio: 'Presentations from 20+ partner organizations showcasing tools, research, and community innovations.',
    venue: 'Exhibition Terrace',
    sessionDescription: 'Interactive exhibition stalls where partners share innovations, published tools, pedagogical resources, and advocacy materials.',
  },

  // Day 3: 11 November 2026
  {
    id: 'sess-8',
    date: '11 November 2026',
    dayNumber: 3,
    time: '09:00 AM - 11:00 AM',
    sessionTitle: 'Joint Action Planning: 2027 Co-Funding & Collective Advocacy',
    speaker: 'Coordination Committee Leads',
    speakerRole: 'Consortium Coordinators',
    speakerBio: 'Coordinating cross-organizational joint action agendas and joint proposals.',
    venue: 'Main Conference Hall',
    sessionDescription: 'Formulating concrete cross-partner coalition pledges, joint advocacy roadmaps, and peer support networks for the year ahead.',
  },
  {
    id: 'sess-9',
    date: '11 November 2026',
    dayNumber: 3,
    time: '11:30 AM - 01:00 PM',
    sessionTitle: 'Closing Plenary, Communiqué Adoption & Next Steps',
    speaker: 'OAK Foundation Leadership & Partner Spokespersons',
    speakerRole: 'Executive Council',
    speakerBio: 'Executive leadership summarizing findings and approving the final convening communiqué.',
    venue: 'Main Conference Hall',
    sessionDescription: 'Adoption of the 2026 Convening Communiqué, vote of thanks, certificates of participation, and concluding lunch.',
  },
];

export const INITIAL_PARTNERS: PartnerOrganization[] = [
  {
    id: 'partner-1',
    name: 'Youth Empowerment Trust (YET)',
    logo: '/partners/yet.svg',
    description: 'Empowering young Zimbabweans through civic participation, vocational training, social entrepreneurship, and leadership development.',
    websiteLink: 'https://yetrust.org.zw',
    contactInformation: {
      email: 'info@yetrust.org.zw',
      phone: '+263 242 700 891',
      address: 'Harare, Zimbabwe',
    },
    fullProfile: 'Youth Empowerment Trust (YET) has been a leading champion for youth civic space and socio-economic empowerment across 8 provinces in Zimbabwe for over 15 years.',
    organizationOverview: 'YET focuses on building resilient youth leaders, incubating community enterprises, and advocating for inclusive national youth policies.',
    areasOfWork: ['Youth Leadership', 'Vocational Skills', 'Civic Engagement', 'Livelihoods Support'],
  },
  {
    id: 'partner-2',
    name: 'Child Rights Coalition Zimbabwe (CRCZ)',
    logo: '/partners/crcz.svg',
    description: 'A coalition of 35 community-based organizations dedicated to advancing children’s rights, safety, and inclusive education.',
    websiteLink: 'https://crczimbabwe.org',
    contactInformation: {
      email: 'secretariat@crczimbabwe.org',
      phone: '+263 242 791 234',
      address: 'Msasa, Harare, Zimbabwe',
    },
    fullProfile: 'CRCZ coordinates national civil society efforts to monitor child rights treaty compliance, eliminate child labor, and guarantee equitable access to quality education.',
    organizationOverview: 'Through sub-partner support, CRCZ operates community child protection committees, legal aid desks, and safe-school advocacy initiatives.',
    areasOfWork: ['Child Protection', 'Education Advocacy', 'Legal Support', 'Community Safeguarding'],
  },
  {
    id: 'partner-3',
    name: 'Eco-Justice Network Zimbabwe',
    logo: '/partners/ecojustice.svg',
    description: 'Championing grassroots climate resilience, sustainable agroecology, and environmental justice for vulnerable rural communities.',
    websiteLink: 'https://ecojusticenw.org.zw',
    contactInformation: {
      email: 'contact@ecojusticenw.org.zw',
      phone: '+263 242 334 556',
      address: 'Bulawayo & Harare, Zimbabwe',
    },
    fullProfile: 'Eco-Justice Network bridges scientific climate adaptation research with indigenous farming practices, supporting smallholder farming cooperatives.',
    organizationOverview: 'Focused on ecological governance, solar water technologies, and seed preservation across drought-prone rural districts.',
    areasOfWork: ['Climate Resilience', 'Agroecology', 'Water Security', 'Community Governance'],
  },
  {
    id: 'partner-4',
    name: 'Zimbabwe Women Lawyers Association (ZWLA)',
    logo: '/partners/zwla.svg',
    description: 'Providing legal aid, rights awareness, and policy reform for women and children facing vulnerability across Zimbabwe.',
    websiteLink: 'https://zwla.co.zw',
    contactInformation: {
      email: 'info@zwla.co.zw',
      phone: '+263 242 708 491',
      address: 'Harare, Zimbabwe',
    },
    fullProfile: 'ZWLA is a premier women’s rights legal organisation offering pro-bono litigation, constitutional rights literacy, and survivor support services.',
    organizationOverview: 'With mobile legal clinics in rural and urban centres, ZWLA serves over 10,000 women and children annually.',
    areasOfWork: ['Legal Aid & Litigation', 'Human Rights Education', 'Gender-Based Violence Prevention', 'Policy Advocacy'],
  },
];
